apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yyhdibn1z-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ab76662d5d.viem.p3.openshiftapps.com/rhtap/rhtap-qe:e01321a453f99083fe680bc68481025800ccc591@sha256:93f31ca3e61f59c745e391853d6210950998029d63f329da541b3eb0a10bf5e7
          name: container-image
